/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OnboardingInviteTeamRouteImport } from './routes/onboarding/invite-team'
import { Route as OnboardingCreateOrgRouteImport } from './routes/onboarding/create-org'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardEmailAccountsRouteImport } from './routes/dashboard/email-accounts'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as DashboardTeamIndexRouteImport } from './routes/dashboard/team/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/dashboard/email/index'
import { Route as DashboardTeamSettingsRouteImport } from './routes/dashboard/team/settings'
import { Route as DashboardTeamMembersRouteImport } from './routes/dashboard/team/members'
import { Route as DashboardTeamInvitationsRouteImport } from './routes/dashboard/team/invitations'
import { Route as DashboardEmailThreadThreadIdRouteImport } from './routes/dashboard/email/thread.$threadId'

const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OnboardingInviteTeamRoute = OnboardingInviteTeamRouteImport.update({
  id: '/onboarding/invite-team',
  path: '/onboarding/invite-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateOrgRoute = OnboardingCreateOrgRouteImport.update({
  id: '/onboarding/create-org',
  path: '/onboarding/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailAccountsRoute = DashboardEmailAccountsRouteImport.update({
  id: '/email-accounts',
  path: '/email-accounts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardTeamIndexRoute = DashboardTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamSettingsRoute = DashboardTeamSettingsRouteImport.update({
  id: '/team/settings',
  path: '/team/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamMembersRoute = DashboardTeamMembersRouteImport.update({
  id: '/team/members',
  path: '/team/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamInvitationsRoute =
  DashboardTeamInvitationsRouteImport.update({
    id: '/team/invitations',
    path: '/team/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailThreadThreadIdRoute =
  DashboardEmailThreadThreadIdRouteImport.update({
    id: '/email/thread/$threadId',
    path: '/email/thread/$threadId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/email/': typeof DashboardEmailIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/dashboard/ai'
    | '/dashboard/billing'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin/'
    | '/dashboard/'
    | '/onboarding'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/email'
    | '/dashboard/team'
    | '/dashboard/email/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/dashboard/ai'
    | '/dashboard/billing'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/email'
    | '/dashboard/team'
    | '/dashboard/email/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/dashboard/ai'
    | '/dashboard/billing'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin/'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/email/'
    | '/dashboard/team/'
    | '/dashboard/email/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AiRoute: typeof AiRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  Verify2faRoute: typeof Verify2faRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingCreateOrgRoute: typeof OnboardingCreateOrgRoute
  OnboardingInviteTeamRoute: typeof OnboardingInviteTeamRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/onboarding/invite-team': {
      id: '/onboarding/invite-team'
      path: '/onboarding/invite-team'
      fullPath: '/onboarding/invite-team'
      preLoaderRoute: typeof OnboardingInviteTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/create-org': {
      id: '/onboarding/create-org'
      path: '/onboarding/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof OnboardingCreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email-accounts': {
      id: '/dashboard/email-accounts'
      path: '/email-accounts'
      fullPath: '/dashboard/email-accounts'
      preLoaderRoute: typeof DashboardEmailAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/team/': {
      id: '/dashboard/team/'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/': {
      id: '/dashboard/email/'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/settings': {
      id: '/dashboard/team/settings'
      path: '/team/settings'
      fullPath: '/dashboard/team/settings'
      preLoaderRoute: typeof DashboardTeamSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/members': {
      id: '/dashboard/team/members'
      path: '/team/members'
      fullPath: '/dashboard/team/members'
      preLoaderRoute: typeof DashboardTeamMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/invitations': {
      id: '/dashboard/team/invitations'
      path: '/team/invitations'
      fullPath: '/dashboard/team/invitations'
      preLoaderRoute: typeof DashboardTeamInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/thread/$threadId': {
      id: '/dashboard/email/thread/$threadId'
      path: '/email/thread/$threadId'
      fullPath: '/dashboard/email/thread/$threadId'
      preLoaderRoute: typeof DashboardEmailThreadThreadIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardEmailAccountsRoute: typeof DashboardEmailAccountsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTeamInvitationsRoute: typeof DashboardTeamInvitationsRoute
  DashboardTeamMembersRoute: typeof DashboardTeamMembersRoute
  DashboardTeamSettingsRoute: typeof DashboardTeamSettingsRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardTeamIndexRoute: typeof DashboardTeamIndexRoute
  DashboardEmailThreadThreadIdRoute: typeof DashboardEmailThreadThreadIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardEmailAccountsRoute: DashboardEmailAccountsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTeamInvitationsRoute: DashboardTeamInvitationsRoute,
  DashboardTeamMembersRoute: DashboardTeamMembersRoute,
  DashboardTeamSettingsRoute: DashboardTeamSettingsRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardTeamIndexRoute: DashboardTeamIndexRoute,
  DashboardEmailThreadThreadIdRoute: DashboardEmailThreadThreadIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AiRoute: AiRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  Verify2faRoute: Verify2faRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingCreateOrgRoute: OnboardingCreateOrgRoute,
  OnboardingInviteTeamRoute: OnboardingInviteTeamRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
